### ISSUE TITLE
Throw an "UnsupportedOperation" exception 

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/jsonpatch-to-mongodb#2]
Add an `else throw new Error('Unsupported Operation ' + p.op + ')` to [patches.map](https://github.com/imlucas/jsonpatch-to-mongodb/blob/master/index.js#L17)

**Comment by thedug** [comment]
See Pull Request: https://github.com/imlucas/jsonpatch-to-mongodb/pull/3
